# Generated by Django 5.0.6 on 2024-06-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobFilterTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_term', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField()),
                ('job_summary', models.TextField()),
                ('job_published', models.DateTimeField()),
                ('job_search_term', models.CharField(max_length=5000)),
                ('job_price_type', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_link', models.TextField()),
                ('search_term', models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
